# Generated by Django 2.1.1 on 2018-09-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_icon',
            field=models.CharField(default='default_icon.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
