# Generated by Django 2.1.1 on 2018-09-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_business_business_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_photo',
            field=models.CharField(default='photo.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
